const WORDS = [
    { 
	chinese: "火旁龍",
 	hakka: "bongˋ liungˇ",
	audio: "火旁龍.wav",
	image: "火旁龍.jpg" },
    {
	chinese: "客家人",
	hakka: "hagˋ gaˊ nginˇ",
	audio: "客家人.wav",
	image: "客家人.jpg" },
    { chinese: "苗栗", hakka: "meuˇ lidˋ", audio: "苗栗.wav", image: "苗栗.jpg" },
    { chinese: "龍", hakka: "liungˇ", audio: "龍.wav", image: "龍.jpg" },
    { chinese: "拜年", hakka: "bai ngienˇ", audio: "拜年.wav", image: "拜年.jpg" },
    { chinese: "平安", hakka: "pinˇ onˊ", audio: "平安.wav", image: "平安.png" },
    { chinese: "龍頭", hakka: "liungˇ teuˇ", audio: "龍頭.wav", image: "龍頭.jpg" },
    { chinese: "桂竹", hakka: "gui zugˋ", audio: "桂竹.wav", image: "桂竹.png" },
    { chinese: "龍珠", hakka: "liungˇ zuˊ", audio: "龍珠.wav", image: "龍珠.png" },
    { chinese: "香火", hakka: "hiongˊ foˋ", audio: "香火.wav", image: "香火.png" },
    { chinese: "燈籠", hakka: "denˊ lungˇ", audio: "燈籠.wav", image: "燈籠.png" },
    { chinese: "鑼鼓", hakka: "loˇ guˋ", audio: "鑼鼓.wav", image: "鑼鼓.png" },
    { chinese: "鼓聲", hakka: "guˋ sangˊ", audio: "鼓聲.wav", image: "鼓聲.png" },
       { chinese: "廟宇", hakka: "giungˊ meu", audio: "廟宇.wav", image: "廟宇.png" },
    { chinese: "伯公(土地公)", hakka: "bagˋ gungˊ", audio: "伯公.wav", image: "伯公.png" },
    { chinese: "祈福", hakka: "kiˇ fugˋ", audio: "祈福.wav", image: "祈福.png" },
    { chinese: "健康", hakka: "kien kongˊ", audio: "健康.wav", image: "健康.png" },
    { chinese: "迎龍", hakka: "ngiangˇ liungˇ", audio: "迎龍.wav", image: "迎龍.jpg" },
    { chinese: "元宵", hakka: "ngienˇ seuˊ", audio: "元宵.wav", image: "元宵.jpg" },
    { chinese: "節慶", hakka: "jiedˋ kin", audio: "節慶.wav", image: "節慶.png" },
       { chinese: "傳統", hakka: "conˇ tungˋ", audio: "傳統.wav", image: "傳統.jpg" },
    { chinese: "驅邪", hakka: "sung sadˋ", audio: "驅邪.wav", image: "驅邪.jpg" },
    { chinese: "吉祥", hakka: "gidˋ xiongˇ", audio: "吉祥.wav", image: "吉祥.jpg" },
    { chinese: "神明", hakka: "siinˇ minˇ", audio: "神明.wav", image: "神明.jpg" }
];
